# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.11.0
_src_path: gl:openscm/copier-core-python-repository
conda_release: false
email: zebedee.nicholls@climate-energy-college.org
include_cli: false
name: Zebedee Nicholls
notebook_based_docs: true
package_manager: uv
pandas_doctests: false
plot_dependencies: true
project_description_short: Demo of setting up a library.
project_name_human: Scratch repo for library demo
project_name_pip: ici-phd-rse
project_name_python: ici_phd_rse
project_url: https://github.com/znicholls/ici-phd-rse-crash-course-scratch
track_lock_file: true
